apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
    - name: pgbouncer
      port: 6432
      protocol: TCP
      targetPort: pgbouncer
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
