apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: metadig-scheduler
  namespace: metadig
spec:
  selector:
    matchLabels:
      app: metadig-scheduler
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: metadig-scheduler
        tier: backend
    spec:
      serviceAccountName: metadig-serviceaccount
      containers:
        - name: metadig-scheduler
          image: docker.io/metadig/metadig-scheduler:2.0.0-rc1
          imagePullPolicy: Always
          volumeMounts:
          - name: nfs-pv
            mountPath: /opt/local
            readOnly: true
      restartPolicy: Always
      volumes:
      - name: nfs-pv
        persistentVolumeClaim:
          claimName: nfs-pvc
