# Load all files in the "config" directory into a ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: metadig-tasks-volume
data:
{{ (tpl (.Files.Glob "config/taskList.csv").AsConfig . ) | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metadig-downloads-list-volume
data:
{{ (tpl (.Files.Glob "config/downloadsList.csv").AsConfig . ) | indent 4 }}
