apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metadig-scheduler.fullname" . }}
  labels:
    {{- include "metadig-scheduler.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "metadig-scheduler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        rollme: {{ randAlphaNum 5 | quote }}
      {{- end }}
      labels:
        {{- include "metadig-scheduler.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "metadig-scheduler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: JAVA_OPTS
            value: "-Dlog4j2.formatMsgNoLookups=true"
          - name: DATAONE_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: dataone-token
                key: DataONEauthToken
                # If 'false", the secret must exist before the pod can start
                # App versions before v2.3.4 will read this value from a config file, not the env var.
                optional: true
          volumeMounts:
          - name: metadig-pv
            mountPath: {{ .Values.persistence.mountPath }}
            readOnly: false
          - name: metadig-config-volume
            mountPath: {{ .Values.persistence.mountPath }}/metadig/metadig.properties
            subPath: metadig.properties
          - name: metadig-tasks-volume
            mountPath: {{ .Values.persistence.mountPath }}/metadig/taskList.csv
            subPath: taskList.csv
          - name: metadig-log4j-volume
            mountPath: {{ .Values.persistence.mountPath }}/metadig/config/log4j.properties
            subPath: log4j.properties
          - name: metadig-downloads-list-volume
            mountPath: {{ .Values.persistence.mountPath }}/metadig/data/downloadsList.csv
            subPath: downloadsList.csv
      volumes:
      - name: metadig-pv
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.claimName }}
      - name: metadig-config-volume
        configMap:
          name: metadig-config-volume
          defaultMode: 0644
      - name: metadig-tasks-volume
        configMap:
          name: metadig-tasks-volume
          defaultMode: 0644
      - name: metadig-log4j-volume
        configMap:
          name: metadig-log4j-volume
          defaultMode: 0644
      - name: metadig-downloads-list-volume
        configMap:
          name: metadig-downloads-list-volume
          defaultMode: 0644
      - name:  {{ .Values.persistence.metacat.claimName }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.metacat.claimName }}
          readOnly: true
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.dns.config}}
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - {{ (lookup "v1" "Service" "kube-system" "kube-dns").spec.clusterIP }}
        searches:
        - metadig.svc.cluster.local
        - svc.cluster.local
        - cluster.local
        options:
        - name: ndots
          value: "5"
      {{- end }}
