{{- if .Values.controller.ingress.enabled -}}
{{- $fullName := printf "%s-controller" (include "metadig.fullname" .) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "metadig.labels" . | nindent 4 }}-controller
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace -}}
            -{{ .Release.Name }}-cors-headers@kubernetescrd"
    {{- with .Values.controller.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.controller.ingress.className }}
  {{- if .Values.controller.ingress.tls }}
  tls:
    {{- range .Values.controller.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.controller.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $.Values.controller.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
