# Load all files in the "config" directory into a ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-volume
data:
  metadig.properties: |
    {{- tpl (.Files.Get .Values.configPath) . | nindent 4 }}

--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-log4j-volume
data:
  log4j.properties: |
    {{- tpl (.Files.Get .Values.logConfigPath) . | nindent 4 }}
