apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metadig.fullname" . }}-controller
  labels:
    {{- include "metadig.labels" . | nindent 4 }}-controller
spec:
  {{- if not .Values.controller.autoscaling.enabled }}
  replicas: {{ .Values.controller.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "metadig.selectorLabels" . | nindent 6 }}-controller
  template:
    metadata:
      {{- with .Values.controller.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        rollme: {{ randAlphaNum 5 | quote }}
      {{- end }}
      labels:
        {{- include "metadig.selectorLabels" . | nindent 8 }}-controller
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "metadig.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-controller
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          ports:
          - name: metadig-tomcat
            containerPort: 8080
            protocol: TCP
          env:
          - name: JAVA_OPTS
            value: "-Dlog4j2.formatMsgNoLookups=true"
          - name: DATAONE_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: dataone-token
                key: DataONEauthToken
                # If 'false", the secret must exist before the pod can start
                # App versions before v2.3.4 will read this value from a config file, not the env var.
                optional: true
          - name: RABBITMQ_AUTH
            valueFrom:
              secretKeyRef:
                name: metadig-rmq-auth
                key: rabbitmq-password
          - name: PG_AUTH
            valueFrom:
              secretKeyRef:
                name: metadig-pg
                key: password          
          volumeMounts:
          - name: metadig-pv
            mountPath: {{ .Values.controller.persistence.mountPath }}
            readOnly: false
          - name: metadig-config-volume
            mountPath: {{ .Values.controller.persistence.mountPath }}/metadig/metadig.properties
            subPath: metadig.properties
          - name: metadig-log4j-volume
            mountPath: {{ .Values.controller.persistence.mountPath }}/metadig/config/log4j.properties
            subPath: log4j.properties
      restartPolicy: Always
      volumes:
      - name: metadig-pv
        persistentVolumeClaim:
          claimName: {{ .Values.controller.persistence.claimName }}
      - name: metadig-config-volume
        configMap:
          name: metadig-config-volume
          defaultMode: 0640
      - name: metadig-log4j-volume
        configMap:
          name: metadig-log4j-volume
          defaultMode: 0640
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.dns.config}}
      dnsPolicy: None
      dnsConfig:
        nameservers:
          {{- $dns := (lookup "v1" "Service" "kube-system" "kube-dns") }}
          - {{ if $dns }}{{ $dns.spec.clusterIP }}{{ else }}10.96.0.10{{ end }}
        searches:
        - metadig.svc.cluster.local
        - svc.cluster.local
        - cluster.local
        options:
        - name: ndots
          value: "5"
      {{- end }}
