apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: metadig
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
  #- name: metadig-httpd
  #  port: 80
  #  protocol: TCP
  #  targetPort: metadig-httpd
  - name: {{ .Chart.Name }}
    port: 8080
    protocol: TCP
    targetPort: metadig-tomcat