{{- if .Values.rabbitmq.enabled }}
### RabbitMQ Cluster Configuration
## --------------------------------------
## This manifest deploys a RabbitMQ cluster using the RabbitMQ Cluster Operator.
## See:
##   https://www.rabbitmq.com/kubernetes/operator/using-operator
##   https://www.rabbitmq.com/docs/production-checklist
##   https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/production-ready

apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ include "metadig.fullname" . }}-rabbitmq
  labels:
    app: rabbitmq
spec:
  secretBackend:
    externalSecret:
      name: {{ .Values.rabbitmq.auth.existingPasswordSecret }}

  {{- if .Values.rabbitmq.affinity }}
    {{- with .Values.rabbitmq.affinity }}
  affinity:
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- else if and .Values.rabbitmq.autoPodAntiAffinity .Values.rabbitmq.autoPodAntiAffinity.enabled }}
  affinity:
    podAntiAffinity:
    {{- if .Values.rabbitmq.autoPodAntiAffinity.force }}
      requiredDuringSchedulingIgnoredDuringExecution:
    {{- else }}
      preferredDuringSchedulingIgnoredDuringExecution:
    {{- end }}
      - weight: {{ .Values.rabbitmq.autoPodAntiAffinity.weight }}
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "metadig.fullname" . }}-rabbitmq
          topologyKey: "kubernetes.io/hostname"
  {{- end }}
  replicas: {{ .Values.rabbitmq.replicaCount }}
  resources:
    {{ toYaml .Values.rabbitmq.resources | nindent 4 }}
  rabbitmq:
    {{- if .Values.rabbitmq.envConfig }}
    envConfig: |
      {{- range $k, $v := .Values.rabbitmq.envConfig }}
      {{ $k }}={{ $v | quote }}
      {{- end }}
    {{- end }}
    {{- if .Values.rabbitmq.additionalConfig }}
    additionalConfig: |
      {{- range $k, $v := .Values.rabbitmq.additionalConfig }}
      {{ $k }} = {{ $v }}
      {{- end }}
    {{- end }}
  persistence:
    storageClassName: {{ .Values.rabbitmq.persistence.storageClassName }}
    storage: {{ .Values.rabbitmq.persistence.size }}
{{- end }}
