apiVersion: v1
kind: ConfigMap
metadata:
  name: metadig-tasks-volume
data:
  taskList.csv: |
    {{- tpl (.Files.Get .Values.tasksPath) . | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metadig-downloads-list-volume
data:
  downloadsList.csv: |
    {{- tpl (.Files.Get .Values.downloadsPath) . | nindent 4 }}