{{- if .Values.scorer.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "metadig.fullname" . }}-scorer
  labels:
    {{- include "metadig.labels" . | nindent 4 }}-scorer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "metadig.fullname" . }}-scorer
  minReplicas: {{ .Values.scorer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.scorer.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.scorer.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.scorer.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.scorer.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.scorer.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
