# Load all files in the "config" directory into a ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configfiles
data:
{{ (tpl (.Files.Glob "config/*").AsConfig . ) | indent 4 }}
