{{- if .Values.persistence.create }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.volumeName }}
spec:
  accessModes:
  - {{ .Values.persistence.accessModes }}
  capacity:
    storage: {{ .Values.persistence.size }}
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: ceph-csi-cephfs
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "{{ .Values.persistence.ceph.clusterID }}"
      "fsName": "{{ .Values.persistence.ceph.fsName }}"
      "staticVolume": "{{ .Values.persistence.ceph.staticVolume }}"
      "rootPath": {{ .Values.persistence.ceph.rootPath }} 
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: cephfs-metadig-pv
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
{{- end }}
