{{- if .Values.persistence.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.claimName }}
spec:
  accessModes:
  - {{ .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  volumeMode: Filesystem
  # volumeName should be same as PV name
  volumeName: {{ .Values.persistence.volumeName }}
{{- end }}
