# value overrides
tasksPath: "config/prod/taskList.csv"
configPath: "config/prod/metadig.properties"

# Set to TRACE, DEBUG, INFO, WARN, or ERROR
logLevel: "DEBUG"

controller:
  ingress:
    hosts:
      - host: api.dataone.org
        paths:
          - path: /quality
            pathType: Prefix
    tls:
        hosts:
          - api.dataone.org

worker:
  replicaCount: 25