# Default values for metadig-worker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

labels:
  app: metadig-worker

image:
  repository: ghcr.io/nceas/metadig-worker
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# The default k8s cluster is "prod". Alternatively, "dev" can be specified.
# This parameter controls which set of configuration files are used.
# - "prod" : use servers from the DataONE production environment
# - "dev" : use servers from the DataONE stage environment
k8s:
  cluster: prod

env:
- name: JAVA_OPTS
  value: "-Dlog4j2.formatMsgNoLookups=true"

tomcat:
  extraCatalinaOpts:
    - -XX:MaxRAMPercentage=75

  jmxEnabled: true

  jmxPort: 9010

  jmxCatalinaOpts:
    - -Dcom.sun.management.jmxremote
    - -Dcom.sun.management.jmxremote.port=9010
    - -Dcom.sun.management.jmxremote.rmi.port=9010
    - -Dcom.sun.management.jmxremote.local.only=false
    - -Dcom.sun.management.jmxremote.authenticate=false
    - -Dcom.sun.management.jmxremote.ssl=false
    - -Djava.rmi.server.hostname=localhost

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "metadig"

podAnnotations: {}

podSecurityContext:
  runAsUser: 59990
  runAsGroup: 59997
  fsGroup: 59990

#topologySpreadConstraints:
#  - maxSkew: 10
#    topologyKey: kubernetes.io/hostname
#    whenUnsatisfiable: ScheduleAnyway
#    labelSelector:
#      matchLabels:
#        app: metadig-worker

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: None

ingress:
  enabled: false

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 4Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  metadig:
    enabled: true
    ## @param persistence.existingClaim
    claimName: "cephfs-metadig-pvc"
    ## @param persistence.storageClass Storage class of backing PVC
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ## set, choosing the default provisioner.
    ##
    storageClass: ""
    accessModes: ReadWriteMany
    size: 20Gi
    ## @param persistence.annotations Persistence annotations for Solr
    ##
    annotations: {}
    ## @param persistence.mountPath Persistence mount path for Solr
    ##
    mountPath: "/opt/local"

  metacat:
    claimName: metadig-repos-rom
    mountPath: "/var/data/repos"

dns:
  config: true
