/*
 * This SQL script creates a database that contains metadata quality
 * reports that are generated by the metadata quality engine.
 */

\connect metadig

ALTER TABLE identifiers ADD COLUMN obsoletes TEXT;
ALTER TABLE identifiers ADD COLUMN obsoleted_by TEXT;
ALTER TABLE identifiers ADD COLUMN sequence_id TEXT;
ALTER TABLE identifiers ADD COLUMN format_id TEXT;
ALTER TABLE identifiers ADD COLUMN rights_holder TEXT;
ALTER TABLE identifiers ADD COLUMN date_uploaded TIMESTAMP WITH TIME ZONE;
ALTER TABLE identifiers ADD COLUMN date_sysmeta_modified TIMESTAMP WITH TIME ZONE;
ALTER TABLE identifiers ADD COLUMN groups TEXT[];
ALTER TABLE identifiers owner to metadig;

ALTER TABLE runs drop column sequence_id;
ALTER TABLE runs drop column is_latest;
