---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metadig
  namespace: metadig

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metadig
  namespace: metadig
rules:
- apiGroups: ["rbac.authorization.k8s.io", "networking.k8s.io", "extensions", "apps", ""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metadig
  namespace: metadig
subjects:
- kind: ServiceAccount
  name: metadig
  namespace: metadig
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metadig


# The following Role and Rolebinding is needed for helm to get the IP address of the kube-dns service.
# This is used to create the DNS config for containers that overrides the default config. Once
# metadig has been upgraded so that a special DNS config is not required by containers, these can
# be removed. For details, see https://github.com/DataONEorg/k8s-cluster/issues/27

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-system-reader
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows metadig to read service descriptions in the kube-system namespace
kind: RoleBinding
metadata:
  name: kube-system-reader
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: metadig
  namespace: metadig
roleRef:
  apiGroup: ""
  kind: Role
  name: kube-system-reader
