/*
 * This SQL script creates a database that contains metadata quality
 * reports that are generated by the metadata quality engine.
 */

CREATE USER metadig;
CREATE DATABASE metadig OWNER metadig;

/* alter database metadig owner to metadig; */

\connect metadig

CREATE TABLE identifiers (
  metadata_id text not null,
  data_source text not null,
  CONSTRAINT metadata_id_pk PRIMARY KEY (metadata_id)
);

alter table identifiers owner to metadig;

CREATE TABLE nodes (
  node_id text not null,
  last_harvest_datetime text not null,
  CONSTRAINT node_id_pk PRIMARY KEY (node_id)
);

alter table nodes owner to metadig;

create TABLE runs (
  metadata_id text not null,
  suite_id  text not null,
  timestamp TIMESTAMP WITH TIME ZONE not null,
  results TEXT not null,
  status text not null, /* Possible values: 'processing', 'error', 'success' */
  error text,
  CONSTRAINT runs_metadata_id_fk FOREIGN KEY (metadata_id) REFERENCES identifiers,
  CONSTRAINT metadata_id_suite_id_fk UNIQUE (metadata_id, suite_id)
);

alter table runs owner to metadig;
