apiVersion: v1
kind: Secret
metadata:
  name: metadig-rmq-auth
type: Opaque
stringData:
  rabbitmq-username: metadig
  rabbitmq-password: CHANGEME
  default_user.conf: |
    default_user = metadig
    default_pass = CHANGEME
