#!/bin/bash

# From https://github.com/bitnami/charts/tree/master/bitnami/solr/#installing-the-chart

#helm repo add bitnami https://charts.bitnami.com/bitnami

helm install metadig-solr bitnami/solr \
--version=3.0.3 \
--namespace metadig \
--set auth.enabled=false \
--set coreNames="quality" \
--set collection="quality" \
--set cloudEnabled=false \
--set image.tag=8.11.1-debian-10-r14 \
--set collectionShards=1 \
--set collectionReplicas=1 \
--set podSecurityContext.enabled=true \
--set podSecurityContext.fsGroup=1001 \
--set containerSecurityContext.enabled=true \
--set containerSecurityContext.runAsUser=1001 \
--set replicaCount=1 \
--set service.type=ClusterIP \
--set service.externalTrafficPolicy=Cluster \
--set ingress.enabled=false \
--set ingress.tls=false \
--set ingress.ingressClassName="nginx" \
--set ingress.hostname="solr.local" \
--set persistence.enabled=true \
--set persistence.mountPath=/bitnami/solr \
--set persistence.storageClass=csi-rbd-sc \
--set persistence.size=20Gi \
--set persistence.mountPath=/bitnami/solr \
--set volumePermissions.enabled=false \
--set volumePermissions.containerSecurityContext.runAsUser=1001 \
--set serviceAccount.create=false \
--set serviceAccount.name="metadig" \
--set tls.enabled=false \
--set tls.autoGenerated=false \
--set tls.certificatesSecretName="ingress-nginx-tls-cert-jks" \
--set tls.passwordsSecretName="metadig-solr/jks-password-secret" \
--set tls.keystorePassword="metadig" \
--set tls.truststorePassword="metadig" \
--set zookeeper.enabled=false \
--set zookeeper.persistence.enabled=false \
--set zookeeper.persistence.storageClass=""
