auth:
  enabled: false

coreNames: "quality"
collection: "quality"
cloudEnabled: false

image:
  registry: docker.io
  repository: bitnamilegacy/solr
  tag: 8.11.4-debian-12-r3

collectionShards: 1
collectionReplicas: 1

podSecurityContext:
  enabled: true
  fsGroup: 1001

containerSecurityContext:
  enabled: true
  runAsUser: 1001

replicaCount: 1

service:
  type: ClusterIP
  externalTrafficPolicy: Cluster

customReadinessProbe:
  exec:
    command:
      - bash
      - -ec
      - >
        curl --silent --connect-timeout 15 http://localhost:${SOLR_PORT_NUMBER}/solr/admin/info/system | grep --quiet '"status":0'
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 15
  successThreshold: 1
  failureThreshold: 6

ingress:
  enabled: false
  tls: false
  ingressClassName: "nginx"
  hostname: "solr.local"

persistence:
  enabled: true
  mountPath: /bitnami/solr
  storageClass: csi-rbd-sc
  size: 20Gi

volumePermissions:
  enabled: false
  containerSecurityContext:
    runAsUser: 1001

serviceAccount:
  create: false
  name: "metadig"

tls:
  enabled: false
  autoGenerated: false
  certificatesSecretName: "ingress-nginx-tls-cert-jks"
  passwordsSecretName: "metadig-solr/jks-password-secret"
  keystorePassword: "metadig"
  truststorePassword: "metadig"

resources:
  requests:
    cpu: 1.0
    memory: 2Gi
  limits:
    cpu: 1.5
    memory: 3Gi

zookeeper:
  enabled: false
  persistence:
    enabled: false
    storageClass: ""

global:
  security:
    allowInsecureImages: true