# value overrides
configPath: "config/dev/metadig.properties"
tasksPath: "config/dev/taskList.csv"

# Set to TRACE, DEBUG, INFO, WARN, or ERROR
loglevel: "DEBUG"

controller:
  ingress:
    hosts:
      - host: api.test.dataone.org
        paths:
          - path: /quality
            pathType: Prefix
    tls:
      - secretName: ingress-nginx-tls-cert
        hosts:
          - api.test.dataone.org