# value overrides
tasksPath: "config/prod/taskList.csv"
configPath: "config/prod/metadig.properties"

# Set to TRACE, DEBUG, INFO, WARN, or ERROR
logLevel: "ERROR"

controller:
  ingress:
    hosts:
      - host: api.dataone.org
        paths:
          - path: /quality
            pathType: Prefix
    tls:
      - secretName: ingress-nginx-tls-cert
        hosts:
          - api.dataone.org