apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadig-worker
  namespace: metadig
spec:
  selector:
    matchLabels:
      app: metadig-worker
      tier: backend
  replicas: 20
  template:
    metadata:
      labels:
        app: metadig-worker
        tier: backend
    spec:
      containers:
      - name: metadig-worker
        image: docker.io/metadig/metadig-worker:2.3.4
        #imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        env:
        - name: JYTHONPATH
          value: "/opt/local/metadig/metadig-py"
        volumeMounts:
        - name: metadig-pv
          mountPath: "/opt/local"
          readOnly: false
      volumes:
      - name: metadig-pv
        persistentVolumeClaim:
          claimName: cephfs-metadig-pvc
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.96.0.10
        searches:
        - metadig.svc.cluster.local
        - svc.cluster.local
        - cluster.local
        options:
        - name: ndots
          value: "5"
