apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadig-controller
  namespace: metadig
spec:
  selector:
    matchLabels:
      app: metadig-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: metadig-controller
    spec:
      containers:
      - name: metadig-controller
        #image: docker.io/metadig/metadig-controller:2.3.1
        image: docker.io/metadig/metadig-controller:2.3.2
        env:
        - name: JAVA_OPTS
          value: "-Dlog4j2.formatMsgNoLookups=true"
        ports:
        - name: metadig-tomcat
          containerPort: 8080
        imagePullPolicy: Always
        volumeMounts:
        - name: metadig-pv
          mountPath: "/opt/local"
          readOnly: true
      volumes:
      - name: metadig-pv
        persistentVolumeClaim:
          #claimName: nfs-pvc
          claimName: cephfs-metadig-pvc
      restartPolicy: Always
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.96.0.10
        searches:
        - metadig.svc.cluster.local
        - svc.cluster.local
        - cluster.local
        options:
        - name: ndots
          value: "5"

---

apiVersion: v1
kind: Service
metadata:
  name: metadig-controller
  namespace: metadig
spec:
  selector:
    app: metadig-controller
  ports:
  - name: metadig-controller
    port: 8080
    protocol: TCP
    targetPort: metadig-tomcat
