apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadig-scheduler
  namespace: metadig
spec:
  selector:
    matchLabels:
      app: metadig-scheduler
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: metadig-scheduler
        tier: backend
    spec:
      serviceAccountName: metadig
      containers:
        - name: metadig-scheduler
          image: docker.io/metadig/metadig-scheduler:2.3.4
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_OPTS
              value: "-Dlog4j2.formatMsgNoLookups=true"
            - name: DATAONE_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dataone-token
                  key: DataONEauthToken
                  # If 'false", the secret must exist before the pod can start
                  optional: false
          volumeMounts:
          - name: metadig-pv
            mountPath: /opt/local
            # Change this to false so filestore ingest can save files from stage to the filestore
            readOnly: false
      restartPolicy: Always
      volumes:
      - name: metadig-pv
        persistentVolumeClaim:
          claimName: cephfs-metadig-pvc
