apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: metadig-controller
  namespace: metadig
spec:
  selector:
    matchLabels:
      app: metadig-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: metadig-controller
    spec:
      containers:
      - name: metadig-controller
        image: docker.io/metadig/metadig-controller:2.2.0
        ports:
        - name: metadig-tomcat
          containerPort: 8080
        imagePullPolicy: Always
        volumeMounts:
        - name: nfs-pv
          mountPath: "/opt/local"
          readOnly: true
      volumes:
      - name: nfs-pv
        persistentVolumeClaim:
          claimName: nfs-pvc
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: metadig-controller
  namespace: metadig
spec:
  selector:
    app: metadig-controller
  ports:
  - name: metadig-controller
    port: 8080
    protocol: TCP
    targetPort: metadig-tomcat