apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: metadig-worker
  namespace: metadig
spec:
  selector:
    matchLabels:
      app: metadig-worker
      tier: backend
  replicas: 75
  template:
    metadata:
      labels:
        app: metadig-worker
        tier: backend
    spec:
      #serviceAccountName: metadig-serviceaccount
      containers:
      - name: metadig-worker
        #image: docker.io/metadig/metadig-worker:2.0.2
        image: docker.io/metadig/metadig-worker:2.2.0dev
        imagePullPolicy: Always
        env:
        - name: JYTHONPATH
          value: "/opt/local/metadig/metadig-py"
        #imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: nfs-pv
          #mountPath: "/etc/metadig"
          mountPath: "/opt/local"
          readOnly: false
      volumes:
      - name: nfs-pv
        persistentVolumeClaim:
          claimName: nfs-pvc
